# Generated by Django 2.0.7 on 2018-07-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='ContactEmail',
        ),
    ]
