version: "3"
services:
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        ports:
            - 8000:8000
        command:
            python manage.py runserver_plus 0.0.0.0:8000
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
